config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  post 'braintree/checkout'
  
	resources :users, only: [:create, :show, :edit, :update]
	resources :recipes
	root 'welcome#index'

	get '/sign_up', to: 'users#new'
	post '/users', to: 'users#create'

	get '/sign_in', to: 'sessions#new'
	post '/sign_in', to: 'sessions#create'
	delete '/sign_out', to: 'sessions#destroy'

	get "/auth/:provider/callback" => "sessions#create_from_omniauth"
end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
	include BraintreeHelper

  def new
    if current_user.address.present? && current_user.city.present? && current_user.state.present? && current_user.zip.present? && current_user.phone_number.present? && current_user.email != "example@gmail.com"
    	@client_token = Braintree::ClientToken.generate
    	@recipe = Recipe.find(params[:recipe_id])
    else
      redirect_to edit_user_path(current_user)
      flash[:danger] =  "Please fill up all the details before proceed to payment!"
    end
  end

  def checkout
  @recipe = Recipe.find(params[:recipe_id])
  nonce_from_the_client = params[:checkout_form][:payment_method_nonce]
  result = Braintree::Transaction.sale(
   :amount => price, #this is currently hardcoded
   :payment_method_nonce => nonce_from_the_client,
   :options => {
      :submit_for_settlement => true
    }
   )

	  if result.success?
	    redirect_to user_path(current_user), :flash => { :success => "Transaction successful!" }
	  else
	    redirect_to user_path(current_user), :flash => { :error => "Transaction failed. Please try again." }
	  end
	end
end

app/helpers/braintree_helper.rb
module BraintreeHelper
	def price
		@recipe.price
	end
end

app/views/braintree/new.html.erb
<p>You're about to order <strong><%= @recipe.title.capitalize %></strong></p> 
<p>The <strong>total price</strong> will be <strong>RM: <%= @recipe.price %></strong></p>
<p>Enter your details to get delivery and start cooking</p>

<div class="demo-frame">
	<%= form_for :checkout_form, url: braintree_checkout_path(recipe_id: @recipe.id), html: {id: "cardForm"} do |form| %> 
		<%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
		<div id="card-number" class="hosted-field"></div>

		<%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
		<div id="expiration_date" class="hosted-field"></div>

		<%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
		<div id="cvv" class="hosted-field"></div>

		<div id="mydiv" data-myval="<%= @client_token %>">
		
		<%= form.hidden_field "payment_method_nonce" %>

		<div class="button-container">
			<%= form.submit "Purchase", disabled: true, class: "button" %>
		</div>
	<% end %>
</div>

<div><%= link_to "Go Back", user_path(current_user) %></div>