config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  post 'braintree/checkout'
  
	resources :users, only: [:create, :show, :edit, :update]
	resources :recipes
	root 'welcome#index'

	get '/sign_up', to: 'users#new'
	post '/users', to: 'users#create'

	get '/sign_in', to: 'sessions#new'
	post '/sign_in', to: 'sessions#create'
	delete '/sign_out', to: 'sessions#destroy'

	get "/auth/:provider/callback" => "sessions#create_from_omniauth"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	belongs_to :user
	has_many :directions
	accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true
	has_many :ingredients
	accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
	mount_uploaders :images, ImageUploader
	self.per_page = 2
	validates :title, presence: true
	validates :description, presence: true
	validates :price, presence: true
	validates :images, presence: true
	default_scope { order(created_at: :desc) }

	def self.search(search)
		if search
			where("title ILIKE :search", search: "%#{search}%")
		else
			all
		end
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	def index
		@recipe = Recipe.search(params[:title])
	end

	def new
		@recipe = Recipe.new
			2.times do
	    @recipe.directions.build
	    @recipe.ingredients.build
	  end
	end

	def create
		@recipe = Recipe.new(recipe_params)
		if @recipe.save
			redirect_to user_path(current_user)
			flash[:success] = "Successfully create recipe listing"
		else
			redirect_to user_path(current_user)
			flash[:notice] = "Fail to create recipe listing. Make sure the field is filled"
		end
	end

	def show
 		@recipe = Recipe.find(params[:id])
 	end

 	def edit
 		@recipe = Recipe.find(params[:id])
 	end

 	def update
 		@recipe = Recipe.find(params[:id])
		if recipe_params
			@recipe.update(recipe_params)
			redirect_to user_path(current_user)
			flash[:success] = "Successfully updated the list"
		else
			render "edit"
			flash[:danger] = "Fail to update the list"
		end
 	end

 	def destroy
 		@recipe = Recipe.find(params[:id])
 		@recipe.destroy
 		respond_to do |format|
 			format.html { redirect_to user_path(current_user) }
 			format.js { render :layout => false }
 		end
 		# @recipe = Recipe.find(params[:id])
		# @recipe.destroy
		# redirect_to user_path(current_user)
		# flash[:success] = "Successfully deleted the list"
 	end

	private

	def recipe_params
		params.require(:recipe).permit(:title, :description, :price, :user_id, {images: []},directions_attributes: [:id, :step, :_destroy], ingredients_attributes: [:id, :name, :_destroy])
	end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_direction_fields.html.erb
<div class="nested-fields">
	<div class="form-group">
		<%= f.label :step %>
		<%= f.text_area :step, class: "form-control" %>
		<%= f.link_to_remove "Remove this step" %>
	</div>	
</div>

app/views/recipes/_form.html.erb
<div id="new_link_div">
	<%= nested_form_for @recipe do |f| %>
	<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class: "form-control" %>
	</div>
	<div class="form-group">
			<%= f.label :description %>
			<%= f.text_area :description, type: 'name', class: "form-control" %>
	</div>
	<div class="form-group">
			<%= f.label :price %>
			<%= f.text_field :price, type: 'name', class: "form-control" %>
	</div>
	<div class="form-group">
			<%= f.label :images %>
			<%= f.file_field :images, multiple: true %>
	</div>

	Ingredients
	<div id="ingredients">
		<%= f.fields_for :ingredients do |ingredient| %>
			<%= render 'ingredient_fields', f: ingredient %>
		<% end %>
			<%= f.link_to_add "Add ingredients", :ingredients %>
	</div>	

	Directions
	<div id="directions">
		<%= f.fields_for :directions do |direction| %>
			<%= render 'direction_fields', f: direction %>
		<% end %>
			<%= f.link_to_add "Add steps", :directions %>
	</div>
	<div class="links">
		<%= f.hidden_field :user_id, :value => current_user.id %>
		<%= f.submit %>
	<% end %>
	</div>

	<%= button_tag "Hide Form", id: "hide_create_form" %>
</div>

app/views/recipes/_ingredient_fields.html.erb
<div class="nested-fields">
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: "form-control" %>
		<%= f.link_to_remove "Remove this ingredient" %>
	</div>
</div>

app/views/recipes/destroy.js.erb
$("#recipe_<%=@recipe.id%>").fadeOut();

app/views/recipes/edit.html.erb
<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
    </div>
    <div class="col-sm-8 text-left"> 
			<%= render partial: 'recipes/form' %>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <h2>List of search results:</h2>           
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Images</th>
        <th>Title</th>
        <th>Description</th>
        <th>Price</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
    <% @recipe.each do |recipe| %>
      <tr id="recipe_<%= recipe.id %>">
        <td><% recipe.images.each do |img| %>
					<p><%= image_tag img %></p>
				</td>
        <td><%= recipe.title.capitalize %></td>
        <td><%= recipe.description.capitalize %></td>
        <td><%= recipe.price %></td>
        <td><%= link_to 'Cook This Meal', recipe_path(recipe.id) %>
      		<% if current_user.superadmin? %>
						<%= link_to 'Edit This Meal', edit_recipe_path(recipe.id) %>
						<%= link_to "Delete", recipe_path(recipe.id), :method => :delete, data: {:confirm => "Are you sure?"}, :remote => true, :class => 'delete_recipe' %>
					<% end %>
				</td>
      </tr>
      	<% end %>
			<% end %>
    </tbody>
  </table>
</div>
	

app/views/recipes/new.html.erb
	<%= render partial: 'recipes/form' %>

app/views/recipes/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');
$('#hide_create_form').click(function(){
	$("#new_link_div").addClass('hidden');
	$('#new_link').show()
})

app/views/recipes/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-4">
    	<% @recipe.images.each do |all_img| %>
				<%= image_tag all_img, class: "img-response" %>
			<% end %>
				<p><strong>Title: </strong><%= @recipe.title.capitalize %></p>
				<p><strong>Description: </strong><%= @recipe.description.capitalize %></p>
				<p><strong>Price in RM: </strong><%= @recipe.price %></p></div>
	  <div class="col-sm-4">
			<h1>Cooking Instructions</h1>

			<% @recipe.directions.each_with_index do |direction, index| %>
				<p><strong>Instruction, <%= index + 1 %></strong></p> 
				<p><%= direction.step.capitalize %></p>
			<% end %>
		</div>
    <div class="col-sm-4">
    	<h1>List of Ingredients</h1>
			
			<% @recipe.ingredients.each_with_index do |ingredient, index| %>
				<p><strong>Ingredient, <%= index + 1 %></strong></p> 
				<p><%= ingredient.name.capitalize %></p>
			<% end %>
		</div>
  </div>
</div>

<div class="container">
    <h1 class="title">A Cooking Timer To Guide Your Cooking :)</h1>
    <h1 id="timerLabel">00:00:00</h1>
    <input type="button" class="myButton" onclick="start()" value="START" id="startBtn">
    <input type="button" class="myButton" onclick="stop()" value="PAUSE">
    <input type="button" class="myButton" onclick="reset()" value="RESET">
</div>

<div><%= link_to "Go Back To Recipe Page", user_path(current_user) %></div>

<div><%= link_to "Make Payment", braintree_new_path(recipe_id: @recipe.id) %></div>